version: "3.8"

services:
  app:
    build:
      args:
        - user=pooja
        - uid=1002
      context: .
      dockerfile: Dockerfile
    container_name: laravel12-app
    user: "${UID}:${GID}"
    volumes:
      - ./:/var/www
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - laravel
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel12-nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    ports:
    - "3307:3306"
    container_name: laravel12-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: laravel12-redis
    ports:
      - "6381:6379"
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
